### ISSUE TITLE
There are SO many improvements which can be made to this plugin...

### ISSUE THREAD

**Issue by jasonwynn10** [McpeBooster/CustomHelp#1]
1. Why is the config file not a resource? Having the server save the config.yml via new Config instances is inefficient.
2. Why are you using the singleton design? It can cause memory leaks.
3. What is with this weird formatting?? https://github.com/McpeBooster/CustomHelp/blob/master/MBCustomHelp%20-%20McpeBooster/src/CustomHelp/CustomHelp.php#L27
https://github.com/McpeBooster/CustomHelp/blob/master/MBCustomHelp%20-%20McpeBooster/src/CustomHelp/CustomHelp.php#L94

**Comment by McpeBooster** [comment]
It should be fixed now :D Thanks for you review
